### ISSUE TITLE
Docker build is not idempotent

### ISSUE THREAD

**Issue by chase-edwards-db** [mspnp/spark-monitoring#110]
When building the library, after the first build attempt, any further attempt to build leads to:
![image](https://user-images.githubusercontent.com/58576405/93798805-7c5c2c80-fbfb-11ea-867f-c300d8288beb.png)

Why is this the case? The build file is clearly in the directory shown, so this appears to be a red herring.

**Comment by hallihan** [comment]
The command from the README is ```docker run -it --rm -v `pwd`/spark-monitoring:/spark-monitoring -v "$HOME/.m2":/root/.m2 maven:3.6.1-jdk-8 /spark-monitoring/build.sh```. The path to the build.sh script at the end of the line should not have `pwd` in it since the command will be run inside of the container.  The first `-v` argument is mounting the directory as `/spark-monitoring` so you should leave command to run inside the container as `/spark-monitoring/build.sh`.

Please reopen the issue if this does not resolve the problem.
