### ISSUE TITLE
Symbol 'term org.eclipse' missing from the classpath while building the jar

### ISSUE THREAD

**Issue by esdhrgl1984** [mspnp/spark-monitoring#116]
Hi All,
I am getting this error while compiling the jar for spark-monitoring in sbt:
_Symbol 'term org.eclipse' is missing from the classpath.
[error] This symbol is required by 'method org.apache.spark.metrics.MetricsSystem.getServletHandlers'.
[error] Make sure that term eclipse is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'MetricsSystem.class' was compiled against an incompatible version of org.
[error]           case Some(metric) => {_

Based on the pom.xml, i have included following dependencies in the build.sbt:

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-library" % "2.11.12",
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-streaming" % sparkVersion % "provided",
  "org.eclipse.jetty" %% "jetty-server" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-core" % sparkVersion % "test",
  "org.scalatest" %% "scalatest" % "3.0.5" % "test",
  "org.junit.jupiter" % "junit-jupiter-api" % "5.3.1" % "test",
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.mockito" % "mockito-core" % "2.21.0" %  "test",
  "com.codahale.metrics" % "metrics-core" % "3.0.2"
)

sparkVersion is 2.4.4
scala version 2.11.12

Can anyone guide what is missing?

**Comment by hallihan** [comment]
The recommended build instructions use Maven and and the configuration handles the dependencies between the spark-listeners_* module and the spark-listeners-loganalytics_* module.  I'm not sure how this would be represented in sbt, but you have to build spark-listeners first, and then spark-listeners-loganalytics has a dependency on the former.

Based on a quick look above, I think you might be missing httpclient (from the main pom.xml in ./src):
```
           <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>${commons.httpclient.version}</version>
                <scope>compile</scope>
            </dependency>
```
The error however seems to indicate a problem finding jetty since that is the only org.eclipse package referenced in [MetricsSystem.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala#L26).  I'm going to close this issue  since building with sbt is outside the scope of the current instructions.  If you get it working, providing the necessary sbt files and build instructions would be a good contribution to suggest via a PR.  Feel free to comment here if you get it working or have other errors, I'll help if I can.
