### ISSUE TITLE
Data of type SparkListenerEvent was dropped because number of fields 1849 is above the limit of 500 custom fields per data type.

### ISSUE THREAD

**Issue by librasonali** [mspnp/spark-monitoring#178]
Hi ,

I am trying to create custom logging for my data brick notebook , for that I followed this repo as it seems an only option for scala codes to have logging in databricks. I followed the steps created the maven project built the jars copied them to dbfs . Now i can see the log analytics workspace created is showing below error. why ? and also What i have to do to print the customs logs only in my log analytics for scala codes ? from cluster . As when 

I am initializing logger like this val logger = Logger.getLogger("SDMmodule")

I was caught into this issue : https://stackoverflow.com/questions/71847138/spark-notserializableexception-when-overriding-log4j-logs/71851912#comment126964522_71848137

Now if again i will initialize will i not get this issue? What snippet of code i have to add in my scala notebooks so that i don't end up to square one. 

Hope you can help !! thank you

getting error in 

<html>
<body>

Data of type SparkListenerEvent was dropped because number of fields 1849 is above the limit of 500 custom fields per data type.
--

<br class="Apple-interchange-newline">
</body>
</html>

![image](https://user-images.githubusercontent.com/40719507/163702772-6ebdfffd-694b-4060-8ec4-e958e56a8d46.png)

**Comment by hallihan** [comment]
We do not currently have instructions for using the library with Notebooks and this scenario has not been tested. This may be possible, and would make a good contribution to the project (see [CONTRIBUTING.md](https://github.com/mspnp/spark-monitoring/blob/main/CONTRIBUTING.md)).

The second case is is a known behavior, called out in the note at https://github.com/mspnp/spark-monitoring#sparklistenerevent_cl

The size and complexity of logs generated by Spark and workload frameworks, like notebooks, has grown considerably since this library was first created.  This library passes through events as-is, only appending a few fields to make the json compatible with ingestion to Log Analytics. We currently don't have a way to parse the events generated by Spark or the workloads to limit the number of fields, and doing so would be be fairly expensive in terms of performance. It is expected that when the workload generates an event with a large number of fields, or that is above the size limit, that you will see these errors and warnings in Log Analytics. You may be able to identify the specific types of events that are causing these errors and use [filtering](https://github.com/mspnp/spark-monitoring/blob/main/docs/filtering.md) to exclude them, or generate a filter that only includes the events you are interested in.
