### ISSUE TITLE
Log4j appender produces StackOverflowErrors when debug logging is turned on

### ISSUE THREAD

**Issue by djoyce-eis** [mspnp/spark-monitoring#26]
When any debug logging is turned on the log4j appender produces a StackOverflowError

This is caused by the appender and it's dependent classes using log4j to log statements during the setup of the appender. This causes and endless loop and so the StackOverFlowError

I believe the correct way to log during log4j initialization is via the LogLog class which outputs to System.out

**Comment by atoakley** [comment]
The logging statements in the Log Analytics clients were removed.  Because the clients are shared between the different pieces, I didn't want to have a hard dependency on log4j.  There is another PR that will be coming that will catch any exceptions from the log4j appender that will use LogLog, so we should be covered. This should be fixed in PR #34
