### ISSUE TITLE
How to use in python notebook

### ISSUE THREAD

**Issue by mikanyg** [mspnp/spark-monitoring#50]
It is not quite clear in the docs how the get python notebooks log to Log Analytics.

I have read about the two options mentioned in #28 

> The reason it works in the sample is because we have configured log4j to log from our sample job package. To use this from a Databricks Notebook, you will need to do the same. There are a couple of options.
> 
> - You can configure the whole cluster to log to Log Analytics, which will include notebooks
> - You can include the code below in every Databricks Notebook. It should work for any notebook because it pulls the class name from the notebook when it runs, but this is lightly tested, so YMMV.

Option A: is that simply the init script does this? Or do I need to configure something extra in order to have all notebooks send logs to log analytics?
Option B: the code is scala, but what about python based notebooks?

Hope you can clear out any confussion I have.

**Comment by atoakley** [comment]
@mikanyg If you are using the library, any logs that Spark generates during the execution of your notebook will automatically go to Log Analytics.

However, if you want to have custom logging messages using the Spark configured log4j, there is a limitation with Python. Logs can only be sent from the driver node because executor nodes do not have access to the JVM from Python. The code below should allow you to log from the driver node using Python.

```python
Logger = spark._jvm.org.apache.log4j.Logger
mylogger = Logger.getLogger(__name__)
mylogger.error("some error trace")
mylogger.info("some info trace")
```
This SO link has some options to log from the executors, but they may not fit your needs.

[https://stackoverflow.com/questions/25407550/how-do-i-log-from-my-python-spark-script](https://stackoverflow.com/questions/25407550/how-do-i-log-from-my-python-spark-script)

**Comment by mikanyg** [comment]
Thx, this worked, at least on the driver nodes. I'll look into options for logging from executor nodes.
