### ISSUE TITLE
spark-monitoring Library is not working for the 6.1, 6.2, 6.3 Databricks Runtime Versions

### ISSUE THREAD

**Issue by azmathasan92** [mspnp/spark-monitoring#68]
When I used this library on 6.0 data bricks runtime version then it is working fine but I want to use the latest version 6.3 with this library. I am facing an error in the init script get failed while the cluster is up.
------------------------------------------------------------------------------------------------------------------
**Event Logs**:
TERMINATING
2020-01-28 11:22:28 IST
Cluster terminated. Reason: Init Script Failure
INIT_SCRIPTS_FINISHED
2020-01-28 11:22:27 IST
Finished Init Scripts execution.
INIT_SCRIPTS_STARTED
2020-01-28 11:22:26 IST
Starting Init Scripts execution.

After Init script finished its execution, it failed.

**The reason is:** 

`Message
Cluster terminated. Reason: Init Script Failure
Init script dbfs:/databricks/spark-monitoring/spark-monitoring.sh failed: Script exit status is non-zero
`

The same script is working fine in the 5.5 and 6.0 data bricks runtime version.

Please Resolve this Issue soon.

**Comment by Smarker** [comment]
Hi @azmathasan92! I'm working on a fix now, but you can refer to my branch https://github.com/Smarker/spark-monitoring/tree/steph/spark-version-fix in the mean time.

I think you just need to add a maven profile for `scala-2.11_spark-2.4.4`. I just tested my branch using a databricks cluster version `6.3` and it ran the init script successfully.

**Comment by mikanyg** [comment]
@Smarker Will the change be backwards compatible, so the cluster init script can work in both 5.5, 6.0 and 6.3 runtimes without altering it?

**Comment by Smarker** [comment]
@mikanyg Yes, because I didn't remove the other pom maven profiles for 5.5, 6.0 (uses spark 2.4.4) This adds just a another maven profile to work on 6.3 which uses spark-2.4.4 and create one more set of listeners jars to use with the newer databricks cluster version.

I'm working on seeing if there's a way now to conditionally build a module, since if you want to run the sample job as well, the pom there still references spark-2.4.3 only and that wouldn't work for newer databricks versions that need spark-2.4.4. Currently on my branch, I build the sample job with all the maven profiles specified [here](https://github.com/mspnp/spark-monitoring/blob/master/build.sh#L7), but it would be nice to be able to conditionally build the sample like how it's set up currently.

**Comment by mikanyg** [comment]
I'm mostly interested in having a single cluster init script that works the same across all supported versions of databricks runtimes. That would make the ops part easy to handle.

But I guess I would need to deploy all jar files (2.4.3 and 2.4.4 versions) to dbfs?

**Comment by Smarker** [comment]
Yes, you would need both 2.4.3 and 2.4.4 if you plan on changing the databricks runtimes. 

Since if you use databricks 6.0-6.3, you'd need jars for spark 2.4.4. If you use databricks 5.5-6.0, you'd need jars for spark 2.4.3.

I just checked and you can use the same init script for both runtimes. The `SPARK_VERSION` and `SPARK_SCALA_VERSION` both work. The change you do need to make is to the main `pom.xml` file and that is to add another spark 2.4.4 maven profile there like I did [here]https://github.com/mspnp/spark-monitoring/compare/master...Smarker:steph/spark-version-fix?expand=1#diff-96d5825f70d1b151527c8384ab158bceR67

**Comment by Smarker** [comment]
Opened a PR out for this if you'd like to try it here: https://github.com/mspnp/spark-monitoring/pull/69

**Comment by atoakley** [comment]
Fixed by #69
